#!/bin/sh

echo '# Pacman (+AUR)'
packer -Syu

echo $'\n# pip3 (System)'
sudo /usr/bin/pip3 install xkeysnail --upgrade

echo $'\n# pip3 (~/venv)'
py_packages_to_update=`pip3 list -o --format=legacy | awk '{print $1}'`
if [ -n "$py_packages_to_update" ]; then
  echo $py_packages_to_update | xargs pip3 install -U
else
  echo 'No package to update'
fi

echo $'\n# Cargo (nightly)'
cargo +nightly install-update rustfmt-nightly

echo $'\n# Cargo (stable)'
cargo install-update -a

echo $'\n# npm (LTS)'
source /usr/share/nvm/init-nvm.sh
nvm use --lts
if [ -n "$(npm outdated)" ]; then
  npm update -g
else
  echo 'No package to update'
fi
