#!/bin/sh

set -e

echo '# Pacman (+AUR)'
packer -Syu

echo $'\n# pip3 (System)'
sudo /usr/bin/pip3 install xkeysnail --upgrade

echo $'\n# pip3 (~/venv)'
packages=`pip3 list -o --format=legacy | awk '{print $1}'`
if [ -n "$packages" ]; then
  echo $packages | xargs pip3 install -U
else
  echo 'No package to update'
fi

echo $'\n# npm (LTS)'
if [ -z "$(npm update -g)" ]; then
  echo 'No package to update'
fi

echo $'\n# Go'
go get -u all

echo $'\n# Cargo'
if cargo install-update clippy rustfmt-nightly cargo-src -l | grep Yes; then
  exit 1
fi
rustup update stable
cargo +stable install-update -ag
