#!/bin/sh

echo '# Pacman (+AUR)'
packer -Syu

echo $'\n# pip3 (System)'
sudo /usr/bin/pip3 install xkeysnail --upgrade

echo $'\n# pip3 (~/venv)'
packages=`pip3 list -o --format=legacy | awk '{print $1}'`
if [ -n "$packages" ]; then
  echo $packages | xargs pip3 install -U
else
  echo 'No package to update'
fi

echo $'\n# Cargo (nightly)'
cargo +nightly install-update clippy rustfmt-nightly

echo $'\n# Cargo (stable)'
cargo +stable install-update -a

echo $'\n# npm (LTS)'
if [ -z "$(npm update -g)" ]; then
  echo 'No package to update'
fi

echo $'\n# GHQ'
ghq get https://github.com/syl20bnr/spacemacs -u
