#!/bin/sh
if [ -f ~/.ghq/github.com/KKPMW/dircolors-moonshine/dircolors.moonshine ]; then
  eval `dircolors ~/.ghq/github.com/KKPMW/dircolors-moonshine/dircolors.moonshine`
fi
exa -lg --git --color-scale --time-style long-iso $@
