[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x75715e"
blue = "0x66d9ef"
cyan = "0xa1efe4"
green = "0xa6e22e"
magenta = "0xae81ff"
red = "0xf92672"
white = "0xf9f8f5"
yellow = "0xf4bf75"

[colors.normal]
black = "0x000000"
blue = "0x66d9ef"
cyan = "0xa1efe4"
green = "0xa6e22e"
magenta = "0xae81ff"
red = "0xf92672"
white = "0xf8f8f2"
yellow = "0xf4bf75"

[colors.primary]
background = "0x282828"
foreground = "0xfbf1c7"

[font]
size = 10.0

[font.bold]
family = "Cica"

[font.bold_italic]
family = "Cica"

[font.italic]
family = "Cica"

[font.normal]
family = "Cica"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Alt"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 1
y = 0
