#!/bin/sh

sxhkd &
# systemctl --user start sxhkd

#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
#bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle true

bspc config top_padding 0
bash ~/.config/bspwm/autostart.sh &

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
#bspc rule -a Chromium desktop='^2'
#bspc rule -a Emacs desktop='^3' state=tiled focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Funkin state=floating

bspc rule -a Matlab-GLEE state=floating

bspc rule -a Alacritty:scratchpad sticky=on layer=above state=tiled hidden=on

#bspc rule -a astroblasto state=floating

bash ~/.config/bspwm/terminal.bash &
