(require 'evil)
(require 'company)
(require 'cl)

(defconst as--lowercase-alphabets (string-to-list "abcdefghijklmnopqrstuvwxyz"))
(defconst as--uppercase-alphabets (string-to-list "ABCDEFGHIJKLMNOPQRSTUVWXYZ"))
(defconst as--numbers (string-to-list "0123456789"))

(defvar autospace-mode-map (make-sparse-keymap))
(defvar autospace/inserted-any-char? nil)

(define-minor-mode autospace-mode
  :init-value nil
  :keymap autospace-mode-map
  (as--init))

(defun as--init ()
  nil)

(defun as--post-self-insert-hook-handler ()
  (with-demoted-errors "as--post-self-insert-hook-handler: %S"
    (when (autospace-mode)
      )))

(defun autospace--self-insert-spacing-when-after (l)
  (let ((p (point)))
    (when (and (member (preceding-char) l) (not (nth 3 (syntax-ppss p))) (not (equal p (line-beginning-position))))
      (insert-char 32))
    (self-insert-command 1)))

(defun autospace--self-insert-spacing-when-not-after (l)
  (let ((p (point)))
    (when (not (or (member (preceding-char) l) (nth 3 (syntax-ppss p)) (equal p (line-beginning-position))))
      (insert-char 32))
    (self-insert-command 1)))

(defun autospace--self-insert-spacing (x)
  (let ((p (point)))
    (when (and x (not (nth 3 (syntax-ppss p))) (not (equal p (line-beginning-position))))
      (insert-char 32))
    (self-insert-command 1)))

(defun autospace--insert-comma ()
  (interactive)
  (self-insert-command 1)
  (when (not (nth 3 (syntax-ppss (point))))
    (insert-char 32)))

(defun my-elisp/self-insert-spacing-when-after (l)
  (let ((p (point)))
    (when (and (member (preceding-char) l) (not (nth 3 (syntax-ppss p))) (not (equal p (line-beginning-position))))
      (insert-char 32))
    (self-insert-command 1)))

(defun my-elisp/self-insert-spacing-when-not-after (l)
  (let ((p (point)))
    (when (not (or (member (preceding-char) l) (nth 3 (syntax-ppss p)) (equal p (line-beginning-position))))
      (insert-char 32))
    (self-insert-command 1)))

(defun autospace-elisp/insert-character ()
  (interactive)
  (my-elisp/self-insert-spacing-when-after '(34 41 93)))

(defun autospace-elisp/insert-pair ()
  (interactive)
  (my-elisp/self-insert-spacing-when-not-after '(32 39 40 91)))

(defun autospace-elisp/insert-colon ()
  (interactive)
  (my-elisp/self-insert-spacing-when-not-after '(32 35)))

(setq company-begin-commands (cons 'autospace-elisp/insert-character company-begin-commands))
(setq company-begin-commands (cons 'autospace-elisp/insert-colon company-begin-commands))

(evil-define-key 'insert emacs-lisp-mode-map "a" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "b" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "c" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "d" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "e" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "f" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "g" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "h" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "i" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "j" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "k" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "l" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "m" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "n" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "o" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "p" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "q" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "r" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "s" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "t" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "u" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "v" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "w" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "x" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "y" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "z" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "A" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "B" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "C" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "D" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "E" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "F" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "G" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "H" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "I" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "J" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "K" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "L" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "M" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "N" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "O" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "P" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "Q" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "R" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "S" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "T" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "U" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "V" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "W" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "X" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "Y" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "Z" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "0" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "1" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "2" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "3" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "4" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "5" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "6" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "7" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "8" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "9" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "!" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "?" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "+" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "-" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "*" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "/" 'autospace-elisp/insert-character)

(evil-define-key 'insert emacs-lisp-mode-map "'" 'autospace-elisp/insert-colon)
(evil-define-key 'insert emacs-lisp-mode-map "#" 'autospace-elisp/insert-character)
(evil-define-key 'insert emacs-lisp-mode-map "(" 'autospace-elisp/insert-pair)
(evil-define-key 'insert emacs-lisp-mode-map "[" 'autospace-elisp/insert-pair)
(evil-define-key 'insert emacs-lisp-mode-map "\"" 'autospace-elisp/insert-pair)


(defun autospace-haskell/insert-alphabet-or-number ()
  (interactive)
  (autospace--self-insert-spacing (and (member (preceding-char) autospace-haskell--chars-for-spacing--vars-and-nums)
                                       (not (autospace-haskell--behind-module-dot?)))))

(defun autospace-haskell/insert-operator ()
  (interactive)
  (autospace--self-insert-spacing-when-not-after autospace-haskell--chars-for-not-spacing--operators))

(defun autospace-haskell/insert-pair ()
  (interactive)
  (autospace--self-insert-spacing-when-not-after autospace-haskell--chars-for-not-spacing--pairs))

(defun autospace-haskell/insert-dot ()
  (interactive)
  (autospace--self-insert-spacing (not (or (member (preceding-char) autospace-haskell--chars-for-not-spacing--operators)
                                           (autospace-haskell--behind-module?)))))

(setq company-begin-commands (append '(autospace-haskell/insert-alphabet-or-number
                                       autospace-haskell/insert-operator
                                       autospace-haskell/insert-dot
                                       autospace-haskell/insert-pair)
                                     company-begin-commands))

(defconst autospace-haskell--characters-for-variables (append as--uppercase-alphabets as--lowercase-alphabets (string-to-list "_'")))
;;(defconst autospace-haskell--initial-characters-for-variables (append as--uppercase-alphabets as--lowercase-alphabets))
;;(defconst autospace-haskell--initial-characters-for-operators (string-to-list "!#$%&*+./<=>?@\\^|-~:"))
;;(defconst autospace-haskell--characters-for-operators (string-to-list "!#$%&*+./<=>?@\\^|-~"))

(defconst autospace-haskell--chars-for-spacing--vars-and-nums (string-to-list ":!#$%&*+./<=>?@^|-~)],"))
(defconst autospace-haskell--chars-for-not-spacing--operators (string-to-list ":!#$%&*+./<=>?@^|-~([ "))
(defconst autospace-haskell--chars-for-not-spacing--pairs (string-to-list "([ "))

(defun autospace-haskell--behind-module? (&optional p)
  (setq p (or p (point)))
  (let ((c (char-before p)))
    (or (member c as--uppercase-alphabets)
        (and (member c autospace-haskell--characters-for-variables)
             (autospace-haskell--behind-module? (- (point) 1))))))

(defun autospace-haskell--behind-module-dot? (&optional p)
  (cond (p
         (let ((c (char-before p)))
           (or (member c as--uppercase-alphabets)
               (and (member c autospace-haskell--characters-for-variables)
                    (autospace-haskell--behind-module-dot? (- (point) 1))))))
        (t
         (and (equal (preceding-char) 46)
              (autospace-haskell--behind-modue-dot? (- (point) 1))))))


(evil-define-key 'insert haskell-mode-map "a" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "b" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "c" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "d" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "e" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "f" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "g" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "h" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "i" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "j" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "k" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "l" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "m" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "n" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "o" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "p" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "q" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "r" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "s" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "t" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "u" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "v" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "w" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "x" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "y" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "z" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "A" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "B" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "C" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "D" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "E" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "F" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "G" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "H" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "I" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "J" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "K" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "L" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "M" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "N" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "O" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "P" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "Q" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "R" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "S" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "T" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "U" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "V" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "W" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "X" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "Y" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "Z" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "0" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "1" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "2" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "3" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "4" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "5" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "6" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "7" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "8" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "9" 'autospace-haskell/insert-alphabet-or-number)
(evil-define-key 'insert haskell-mode-map "!" 'autospace-haskell/insert-operator)
(evil-define-key 'insert haskell-mode-map "?" 'autospace-haskell/insert-operator)
(evil-define-key 'insert haskell-mode-map "+" 'autospace-haskell/insert-operator)
(evil-define-key 'insert haskell-mode-map "-" 'autospace-haskell/insert-operator)
(evil-define-key 'insert haskell-mode-map "*" 'autospace-haskell/insert-operator)
(evil-define-key 'insert haskell-mode-map "/" 'autospace-haskell/insert-operator)
(evil-define-key 'insert haskell-mode-map "#" 'autospace-haskell/insert-operator)
(evil-define-key 'insert haskell-mode-map "$" 'autospace-haskell/insert-operator)
(evil-define-key 'insert haskell-mode-map "%" 'autospace-haskell/insert-operator)
(evil-define-key 'insert haskell-mode-map "&" 'autospace-haskell/insert-operator)
(evil-define-key 'insert haskell-mode-map "/" 'autospace-haskell/insert-operator)
(evil-define-key 'insert haskell-mode-map "<" 'autospace-haskell/insert-operator)
(evil-define-key 'insert haskell-mode-map "=" 'autospace-haskell/insert-operator)
(evil-define-key 'insert haskell-mode-map ">" 'autospace-haskell/insert-operator)
(evil-define-key 'insert haskell-mode-map "@" 'autospace-haskell/insert-operator)
(evil-define-key 'insert haskell-mode-map "^" 'autospace-haskell/insert-operator)
(evil-define-key 'insert haskell-mode-map "|" 'autospace-haskell/insert-operator)
(evil-define-key 'insert haskell-mode-map "-" 'autospace-haskell/insert-operator)

(evil-define-key 'insert haskell-mode-map "." 'autospace-haskell/insert-dot)
(evil-define-key 'insert haskell-mode-map ":" 'autospace-haskell/insert-operator)

(evil-define-key 'insert haskell-mode-map "(" 'autospace-haskell/insert-pair)
(evil-define-key 'insert haskell-mode-map "[" 'autospace-haskell/insert-pair)
(evil-define-key 'insert haskell-mode-map "'" 'autospace-haskell/insert-pair)
(evil-define-key 'insert haskell-mode-map "`" 'autospace-haskell/insert-pair)
(evil-define-key 'insert haskell-mode-map "\"" 'autospace-haskell/insert-pair)
